@host = https://paleobiodb.org/data1.2/

//get all intervals with start and end myas
GET {{host}}occs/list.json?all_records
###

GET {{host}}occs/list.json?base_name=homo&show=coords

###
# This operation returns a list of the most prevalent taxa (according to number of occurrences) from among the selected set of fossil occurrences. These taxa will be phyla and/or classes, depending upon the size of the list and the requested number of entries. Major taxa that are roughly at the level of classes may be included even if they are not not formally ranked at that level. Unlike most of the operations of this data service, the parameter limit is significant in determining the elements of the result. A larger limit will tend to show classes instead of phyla. For example:
# https://paleobiodb.org/data1.2/occs_doc.html
GET {{host}}}occs/diversity.txt?base_name=Dinosauria^Aves&continent=NOA&count=genera

###
# show the diversity of a group
# We can join on interval name to intervals to get a timeline
GET {{host}}occs/diversity.json?base_name=mammalia
###
# Displays the most prevelant taxa in the database
GET {{host}}occs/prevalence.json?continent=noa&interval=mesozoic&limit=10

###
GET {{host}}occs/list.json?vocab=pbdb&all_records&interval=permian

###
GET http://localhost:8080/intervals
###
GET http://localhost:8080/diversity

###
GET https://paleobiodb.org/data1.2/occs/list.json?&interval_id=652&vocab=pbdb&show=attr,class,phylo,genus,subgenus,ident,img,plant,abund,ecospace,coords,env,geo,paleoloc,loc,coll,taphonomy,timecompare,strat,time HTTP/1.1

###
# 957 - 
# Lopingian 

# 652,Olenekian,247.2
# 653,Induan,251.2
# 3,Paleozoic,251.902
# 17,Permian,251.902
# 771,Lopingian,251.902
# 715,Changhsingian,251.902
# 716,Wuchiapingian,254.14

    "errors": [

   "bad value 'all_records' for 'show': must be one of 'full', 'acconly', 'attr', 'class', 'classext', 'phylo', 'genus', 'subgenus', 'ident', 'rem', 'img', 'plant', 'abund', 'ecospace', 'ttaph', 'taphonomy', 'etbasis', 'pres', 'coll', 'coords', 'loc', 'bin', 'paleoloc', 'prot', 'time', 'timebins', 'timecompare', 'strat', 'stratext', 'lith', 'lithext', 'methods', 'env', 'geo', 'ctaph', 'comps', 'ref', 'refattr', 'resgroup', 'ent', 'entname', 'crmod'"
    ],